version: '3.3'

volumes:
  web_data:
  static:
  media:

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
#      - web_data:/usr/src/app
      - static:/backend/static
      - media:/backend/mediafiles
#      - ./backend:/backend
#      - /Volumes:/static
#      - /Users:/media
    expose:
      - 8000

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - web_data:/usr/src/app

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - web_data:/usr/src/app
      - static:/backend/static
      - media:/backend/mediafiles
#      - /Volumes:/static
#      - /Users:/frontend/media
#  pg_data:
#  static_data:
