# Generated by Django 4.2.4 on 2023-09-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('brand', models.CharField(default='', max_length=10000, null=True, verbose_name='Брэнд')),
                ('type', models.CharField(default='', max_length=10000, null=True, verbose_name='Тип одежды')),
                ('size', models.CharField(default='', max_length=10000, null=True, verbose_name='Размер')),
                ('description', models.CharField(default='', max_length=10000, null=True, verbose_name='Комментарий от клиента')),
                ('comment', models.CharField(default='', max_length=10000, null=True, verbose_name='Комментарий по закупке')),
                ('status_ch', models.CharField(default='', max_length=10000, null=True, verbose_name='Статус Китай')),
                ('status_rf', models.CharField(default='', max_length=10000, null=True, verbose_name='Статус Россия')),
                ('country', models.CharField(default='', max_length=10000, null=True, verbose_name='Страна доставки')),
                ('price_cl', models.CharField(default='', max_length=10000, null=True, verbose_name='Цена розничная')),
                ('price_fc', models.CharField(default='', max_length=10000, null=True, verbose_name='Цена закупочная')),
                ('frontend', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
