# Generated by Django 4.2.4 on 2023-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Комментарий по закупке'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Страна доставки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Комментарий от клиента'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_cl',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Цена розничная'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_fc',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Цена закупочная'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status_ch',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Статус Китай'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status_rf',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Статус Россия'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='type',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Тип одежды'),
        ),
    ]
