# Generated by Django 4.2.4 on 2023-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_sale_brand_alter_sale_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
