# Generated by Django 4.2.4 on 2023-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_sale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='num_order',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
