# Generated by Django 4.2.5 on 2023-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_sale_num_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='frontend',
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Данные клиента'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=None, verbose_name='Время создания'),
        ),
    ]
