# Generated by Django 4.2.4 on 2023-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_sale_num_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='frontend',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Данные клиента'),
        ),
    ]
